# Generated by Django 3.2.5 on 2021-07-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(max_length=30)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('epsilon', models.IntegerField()),
                ('keywords', models.CharField(max_length=100)),
            ],
        ),
    ]
