# Generated by Django 3.2.5 on 2021-07-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_checkin_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='userId',
            new_name='User_ID',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='longitude',
            new_name='long',
        ),
    ]
